name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: slack-assistant
  REGION: us-central1
  REPOSITORY: docker-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push container
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          timeout: 300s
          flags: '--platform=managed --allow-unauthenticated --port=3000 --max-instances=10 --memory=512Mi --cpu=1 --service-account=slack-assistant@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
          env_vars: |-
            NODE_ENV=production
            API_KEY=${{ secrets.API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            SLACK_MCP_SERVER_URL=${{ vars.SLACK_MCP_SERVER_URL }}
            AZURE_MCP_SERVER_URL=${{ vars.AZURE_MCP_SERVER_URL }}
            ATLASSIAN_MCP_SERVER_URL=${{ vars.ATLASSIAN_MCP_SERVER_URL }}
            HOME_PAGE_URL=${{ vars.HOME_PAGE_URL }}
            SLACK_CLIENT_ID=${{ vars.SLACK_CLIENT_ID }}
            SLACK_CLIENT_SECRET=${{ secrets.SLACK_CLIENT_SECRET }}
            SLACK_STATE_SECRET=${{ secrets.SLACK_STATE_SECRET }}
            SLACK_REDIRECT_URI=${{ vars.SLACK_REDIRECT_URI }}
            AZURE_CLIENT_ID=${{ vars.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID=${{ vars.AZURE_TENANT_ID }}
            AZURE_REDIRECT_URI=${{ vars.AZURE_REDIRECT_URI }}
            ATLASSIAN_CLIENT_ID=${{ vars.ATLASSIAN_CLIENT_ID }}
            ATLASSIAN_CLIENT_SECRET=${{ secrets.ATLASSIAN_CLIENT_SECRET }}
            ATLASSIAN_REDIRECT_URI=${{ vars.ATLASSIAN_REDIRECT_URI }}
          env_vars_update_strategy: overwrite

      - name: Get service URL
        run: |
          echo "Service deployed to:"
          gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)'